// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dlchat-aurora/AuroraPremium.tsx": () => import("../components/mockups/dlchat-aurora/AuroraPremium.tsx"),
  "./components/mockups/dlchat-crystal/CrystalClean.tsx": () => import("../components/mockups/dlchat-crystal/CrystalClean.tsx"),
  "./components/mockups/dlchat-obsidian/ObsidianDark.tsx": () => import("../components/mockups/dlchat-obsidian/ObsidianDark.tsx")
};
